name: "F5XC WAF on RE AWS Destroy"

on:
  push:
    branches:
      - destroy-waf-re-aws
  pull_request:
  workflow_dispatch:

jobs:

  terraform_xc:
    name: "F5XC WAF"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws/waf-re-aws/xc
    env:
      TF_VAR_tf_cloud_organization:    ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_VAR_tf_cloud_workspace_infra: ${{ vars.TF_CLOUD_WORKSPACE_AWS_INFRA }}
      TF_VAR_tf_cloud_workspace_vm:    ${{ vars.TF_CLOUD_WORKSPACE_AWS_VM }}
      TF_VAR_api_url:                  ${{ secrets.XC_API_URL }}
      TF_VAR_xc_namespace:             ${{ vars.XC_NAMESPACE }}
      TF_VAR_app_domain:               ${{ vars.APP_DOMAIN }}
      TF_VAR_xc_waf_blocking:          ${{ vars.XC_WAF_BLOCKING }}
      TF_VAR_p12_password:             ${{ secrets.XC_P12_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > backend.tf << EOF
          terraform {
            cloud {
              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
              workspaces {
                name = "${{ vars.TF_CLOUD_WORKSPACE_AWS_XC }}"
              }
            }
          }
          EOF
          echo "${{ secrets.XC_API_P12_FILE }}" | base64 -d > api.p12

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Destroy
        if: (github.ref == 'refs/heads/destroy-waf-re-aws' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve -input=false

  terraform_vm:
    name: "AWS VM (Arcadia)"
    runs-on: ubuntu-latest
    needs: terraform_xc
    defaults:
      run:
        working-directory: ./aws/waf-re-aws/vm
    env:
      AWS_ACCESS_KEY_ID:               ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY:           ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_tf_cloud_organization:    ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_VAR_tf_cloud_workspace_infra: ${{ vars.TF_CLOUD_WORKSPACE_AWS_INFRA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Extract SSH public key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          SSH_PUBLIC_KEY=$(ssh-keygen -y -f /tmp/id_rsa)
          rm -f /tmp/id_rsa
          echo "TF_VAR_ssh_key=${SSH_PUBLIC_KEY}" >> $GITHUB_ENV

      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > backend.tf << EOF
          terraform {
            cloud {
              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
              workspaces {
                name = "${{ vars.TF_CLOUD_WORKSPACE_AWS_VM }}"
              }
            }
          }
          EOF

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Destroy
        if: (github.ref == 'refs/heads/destroy-waf-re-aws' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve -input=false

  terraform_infra:
    name: "AWS Infra"
    runs-on: ubuntu-latest
    needs: terraform_vm
    defaults:
      run:
        working-directory: ./aws/waf-re-aws/infra
    env:
      AWS_ACCESS_KEY_ID:            ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY:        ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_tf_cloud_organization: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_VAR_aws_region:            ${{ vars.AWS_REGION }}
      TF_VAR_project_prefix:        ${{ vars.PROJECT_PREFIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > backend.tf << EOF
          terraform {
            cloud {
              organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
              workspaces {
                name = "${{ vars.TF_CLOUD_WORKSPACE_AWS_INFRA }}"
              }
            }
          }
          EOF

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Destroy
        if: (github.ref == 'refs/heads/destroy-waf-re-aws' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve -input=false
